import React, { createContext, useContext, useEffect, useState } from 'react';
import useSound from 'use-sound';
import { useTheme } from '../../context/ThemeContext';

// Local assets - Generated by python script
const SOUNDS = {
  AMBIENT_NORMAL: '/sounds/ambient-normal.wav', 
  AMBIENT_UPSIDE_DOWN: '/sounds/ambient-upside-down.wav',
  HOVER: '/sounds/hover.wav',
  CLICK: '/sounds/click.wav',
  TRANSITION: '/sounds/transition.wav'
};

type SoundContextType = {
  playHover: () => void;
  playClick: () => void;
  playTransition: () => void;
  isMuted: boolean;
  toggleMute: () => void;
};

const SoundContext = createContext<SoundContextType | undefined>(undefined);

export const SoundProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [isMuted, setIsMuted] = useState(true); // Default to muted for browser policy
  const { isUpsideDown } = useTheme();

  // Sounds
  const [playHover] = useSound(SOUNDS.HOVER, { volume: 0.2, soundEnabled: !isMuted });
  const [playClick] = useSound(SOUNDS.CLICK, { volume: 0.5, soundEnabled: !isMuted });
  const [playTransition] = useSound(SOUNDS.TRANSITION, { volume: 0.6, soundEnabled: !isMuted });

  // Ambient Tracks
  const [playNormalAmbient, { stop: stopNormal }] = useSound(SOUNDS.AMBIENT_NORMAL, { 
    volume: 0.3, 
    loop: true,
    soundEnabled: !isMuted,
    interrupt: true
  });
  
  const [playUpsideDownAmbient, { stop: stopUpsideDown }] = useSound(SOUNDS.AMBIENT_UPSIDE_DOWN, { 
    volume: 0.4, 
    loop: true,
    soundEnabled: !isMuted,
    interrupt: true
  });

  // Handle Ambience Switching
  useEffect(() => {
    if (isMuted) {
      stopNormal();
      stopUpsideDown();
      return;
    }

    // Stop all first ensuring no overlap
    stopNormal();
    stopUpsideDown();

    if (isUpsideDown) {
      playUpsideDownAmbient();
    } else {
      playNormalAmbient();
    }

    return () => {
      stopNormal();
      stopUpsideDown();
    };
  }, [isMuted, isUpsideDown, playNormalAmbient, playUpsideDownAmbient, stopNormal, stopUpsideDown]);

  // Transition Effect
  useEffect(() => {
    if (!isMuted) {
      playTransition();
    }
  }, [isUpsideDown, playTransition, isMuted]);

  const toggleMute = () => setIsMuted(prev => !prev);

  return (
    <SoundContext.Provider value={{
      playHover,
      playClick,
      playTransition,
      isMuted,
      toggleMute
    }}>
      {children}
    </SoundContext.Provider>
  );
};

export const useSoundEffects = () => {
  const context = useContext(SoundContext);
  if (context === undefined) {
    throw new Error('useSoundEffects must be used within a SoundProvider');
  }
  return context;
};
